### PR TITLE
Move CommentNode rep mochitest to jest

### PR DESCRIPTION
**Pull request by jakub-c**
Based on #415

### CODE REVIEW

**Comment by arashm** [comment]
@nchevobbe I believe your approach is better. I think I will update #435 to follow the same pattern.

**Comment by sidthesloth92** [comment]
@nchevobbe Yours look much succint. Will follow your when I take up new ones.

**Comment by jakub-c** [comment]
@nchevobbe I followed your example and I wrapped all text rendering tests in one `it` block.

**Comment by jasonLaster** [comment]
Thanks @jakub-c! By the way, you should stop by our #reps channel in slack!

https://devtools-html.slack.com

**Pull request merged**
