### PR TITLE
Add collapse logic to vertical splitbox.

### PR DESCRIPTION
**Pull request by wldcordeiro**
This adds the collapse logic to the vertical `Splitbox`

### CODE REVIEW

**Comment by wldcordeiro** [comment]
Weird that we don't require review here, also I seem to lack team access?

**Comment by juliandescottes** [comment]
@wldcordeiro added mandatory reviews and added you as a collaborator.

**Comment by wldcordeiro** [comment]
@jasonLaster I'm still trying to figure out this collapse. Height is weird, setting it to zero doesn't do the trick since the children elements have height.

**Comment by jasonLaster** [comment]
@wldcordeiro I think I figured out what to do here. 

Let's punt! I don't think we need to vertically collapse the bottom Panè honestly. 

There's plenty of wins without it :)

**Comment by jasonLaster** [comment]
closing this, we can always come back to it

**Pull request closed without merging**
