### PR TITLE
Update babel-eslint and bump launchpad to 0.0.114

### PR DESCRIPTION
**Pull request by nchevobbe**
This is likely to fix https://github.com/devtools-html/debugger.html/issues/5068 (see https://github.com/eslint/eslint/issues/9767#issuecomment-353840674)

### CODE REVIEW

**Comment by nchevobbe** [comment]
CI is failing because of devtools-license-check complaining about pako being MIT **and** Zlib.
pako is not requested directly and is probably a dependency of babel-eslint.

I'm unsure what should be done here.

**Comment by nchevobbe** [comment]
[Zlib license](https://spdx.org/licenses/Zlib.html) seems pretty good for us. Should we add it to devtools-license-check valid licences ? @captainbrosset do you have an opinion on this ?

**Comment by codehag** [comment]
good question -- im not too sure how to review this. pbro and @jasonLaster probably have a good idea though. I don't know if we need to clear this with any legal agents... would be good to know!

**Comment by captainbrosset** [comment]
If this is a devDependency, then we should be fine, no need to check anything, we're not shipping or embedding code anywhere. And looking at the mentioned issue, I guess this is or should be a devDependency.

It it's not, then that means we're distributing Pako with our software and should therefore make sure its license is a compatible one.
It looks like it is, so feel free to open a PR against the license-checker and ask Tom for a quick review.

**Comment by nchevobbe** [comment]
So it is a direct dependency at the moment, in the devtools-launchpad package (which we publish).
@jasonLaster is there any reason to keep it as a dependency and not a dev one ?
Also, can't we have this dependency as a devDependency on the debugger instead ?

**Comment by jasonLaster** [comment]
we can make it a devDependency.

The debugger now has devDependencies for the eslint plugins

**Comment by nchevobbe** [comment]
the dependency was added in debugger and now everything is fine (after releasing a new version of devtools-licenes-check to support Zlib).
Let's put that aside for now

**Pull request closed without merging**
