### PR TITLE
Add length postfix for arraylike reps

### PR DESCRIPTION
**Pull request by kootoopas**
Associated Issue: #566

### Summary of Changes

Display length postfix in title of arraylike objects (Arrays, Sets, etc).

### Test Plan

Apart from syncing the unit tests, here's a screenshot of arraylike objects:

screen shot 2017-12-16 at 5 38 21 pm

Example test plan:

- Click the `array`, `map & sets` and the `promise` buttons in the reps gui to see for yourself. :)

### CODE REVIEW

**Comment by kootoopas** [comment]
UX seems to be fine with large arrays too. :)

screen shot 2017-12-16 at 6 22 25 pm

**Comment by nchevobbe** [comment]
Thank you very much @kootoopas . I am still unsure if it is useful to have the length. I'd like to run a quick survey to see if people need this, probably in the beginning in the week so we get enough feedback to take a decision here :)

**Comment by jasonLaster** [comment]
This looks nice :)

**Comment by kootoopas** [comment]
I merged master to this one and updated rendering of title accordingly. Although I am not sure if that's the way to properly stay in sync with master, since changes made by other people seem to get annotated with my name. 🤔 
screen shot 2017-12-30 at 7 07 55 pm

I'm probably causing trouble because this is new to me. 😅

**Comment by nchevobbe** [comment]
Oooops, your PR seems to have many changes not related to this issue :D 
Could you take a look ?

**Comment by kootoopas** [comment]
@nchevobbe Yeah, I figured... Working on it!

**Comment by kootoopas** [comment]
Soooo, I'm closing this trainwreck of a pr (😅) and I'm opening another one (#881), because I couldn't figure how to reflect the rebased changes on my existing github branch.

**Pull request closed without merging**
