### PR TITLE
Modify ObjectWithText to show the class of the object

### PR DESCRIPTION
**Pull request by weilonge**
Associated Issue: #684

Implement CSSRule reps for showing CSSStyleRule node.

### CODE REVIEW

**Comment by weilonge** [comment]
@nchevobbe Could you help to review this patch?

**Comment by nchevobbe** [comment]
@weilonge sure !

So CI is not happy right now. It seems that the `supportObject` function from `css-rule` throws with some object: 
```
TypeError: Cannot read property 'class' of undefined
at Object.supportsObject (/home/ubuntu/devtools-core/packages/devtools-reps/src/reps/css-rule.js:31:16)
```
which is 
```js
function supportsObject(object, noGrip = false) {
  return object.class == "CSSStyleRule";
}
```
we should check if we have a truthy object before checking `object.class`

**Comment by weilonge** [comment]
Thank you for the patch to fix the test. I am going through all errors and fixing them.

**Comment by nchevobbe** [comment]
So it looks like these kind of grips (CSSStyleRule & CSSMediaRule) are handled by the ObjectWithText rep.
So we need to apply the logic we put in CSSRuleRep from this PR to ObjectWithText, and adapt the tests.
Also, the current test is only for a CSSStyleRule, we should have one for CSSMediaRule.
Here's a CSSMediaRule grip that we can put in a stub in order to test it : 
```js
{
    "type": "object",
    "actor": "server2.conn8.child17/obj30",
    "class": "CSSMediaRule",
    "extensible": true,
    "frozen": false,
    "sealed": false,
    "ownPropertyLength": 0,
    "preview": {
      "kind": "ObjectWithText",
      "text": "(min-height: 680px), screen and (orientation: portrait)"
    }
  }
```

**Pull request merged**
