### PR TITLE
Use webpack Node api over creating system process

### PR DESCRIPTION
**Pull request by Garbee**
This allows the script to be ran in Windows where it currently is failing for whatever reason.

**Warning** I've only done the most superficial test of using yarn to link to reps and running reps install to see if I got the site to run after doing `yarn start`. Beyond that, I really have no idea what to look for to verify this is working as it was before.

### CODE REVIEW

**Comment by janodvarko** [comment]
I am able to successfully run `yarn install` for devtools-core but, not for `devtools-reps`. Is this pull request supposed to fix also `devtools-reps` module?

Honza

**Comment by jasonLaster** [comment]
@janodvarko you can comment out the prepublish line in the reps package.Json file and it should  work.

**Comment by Garbee** [comment]
I'll be looking at this again in the morning. Just got home and am extremely tired.

**Comment by Garbee** [comment]
@janodvarko Give `yarn upgrade` a shot. I think we just need to update the yarn lock as it works after that here in Windows 7. (PRing the lock update now.)

**Comment by Garbee** [comment]
And ignore that. `upgrade` works since it isn't triggering the webpack build. Investigating more...

**Comment by Garbee** [comment]
So, the problem is the last version bump was `0.0.29` which was just before this PR was merged. So even a fully updated `launchpad` version doesn't have the fix. Once we get a `0.0.30` tagged and we upgrade the dep in reps it will work just fine.

Thanks for catching that @janodvarko!

**Comment by janodvarko** [comment]
Works for me now, thanks!

Honza

**Pull request merged**
