### PR TITLE
add search-box component into sham-modules

### PR DESCRIPTION
**Pull request by gasolin**
add search-box and tabs component into `devtools-sham-modules` since they have dependencies in `sham-modules`.

put requires in alphabet order.

(I'm not sure if its fine to add shortcut in index.js, with that way the unused `search-box` component will be bundled into `debugger.html`)

### CODE REVIEW

**Comment by gasolin** [comment]
The patch works with Netmonitor.html prove-of-concept version https://github.com/gasolin/devtools-core/tree/netmonitor.html/packages/netmonitor

And we plan to use the same module dependency in gecko (via webpack alias)

**Comment by wldcordeiro** [comment]
@gasolin odd question but do you think we could maybe reuse our [searchbar](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/SearchBar.js) in the debugger.html project or [tabs](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Tabs.js) component? It might be a tall order to do this change but I'm open to helping. Seems weird to have an implementation of tabbed interface in the `devtools-core` and one in the debugger.

**Comment by jasonLaster** [comment]
Thanks @gasolin.

@wldcordeiro we can reconcile the different search bars at a later point. Right now the netmonitor team is mostly looking to be in a position where they can easily use the launchpad.

**Comment by gasolin** [comment]
@wldcordeiro thanks for aware that. At the end we should have 1 component to deal with similar things. I'll create an issue to note that, but for current phase we can keep these components as it is, focus on make things happen, then make the code base looks like what it should be.

**Pull request merged**
