### PR TITLE
Release 0.12.4

### PR DESCRIPTION
**Pull request by juliandescottes**
This is just a cherry pick of bc7bb952d66685c709216a675b3d674856df1c32 on top of reps v0.12.3.

It would solve https://github.com/devtools-html/debugger.html/issues/4639 which would really be nice to get in before 58 ships IMO.

### CODE REVIEW

**Comment by juliandescottes** [comment]
Not sure how this should be merged though.

**Comment by nchevobbe** [comment]
Thanks for doing this @juliandescottes .
Not sure what we should do with that too

**Comment by juliandescottes** [comment]
Thanks for having a look, I guess we need to branch from 0.12.3 ?

**Comment by nchevobbe** [comment]
yes, it sounds good

**Comment by juliandescottes** [comment]
Let's wait to see if @jasonLaster is ok with the approach for the debugger then. After all that's the only reason why this version is needed.

**Comment by jasonLaster** [comment]
ooh. I like this idea, it takes the pressure off the reduxification effort. I think we can do this as long as we merge into a 12x branch. and then NPM publish.

Thanks @juliandescottes

**Comment by juliandescottes** [comment]
Cool! I created the branch, should be ready to merge and publish.

**Comment by nchevobbe** [comment]
great, thanks a lot @juliandescottes  !
I'll think of doing this in the future if a similar thing happens

**Comment by juliandescottes** [comment]
You're welcome :) Thanks for carefully tagging all the releases so far, would have been a nightmare without this.

**Pull request merged**
