### PR TITLE
Bump source maps

### PR DESCRIPTION
**Pull request by jasonLaster**
bumping the source maps lib to include an up to date version of mappings

### CODE REVIEW

**Comment by tromey** [comment]
It's possible you'll run into the problem that caused https://github.com/mozilla/source-map/pull/289

**Comment by jasonLaster** [comment]
i don't follow...

**Comment by tromey** [comment]
Sorry - just that devtools-source-map is slightly broken because source-map is slightly broken; and until that PR lands you may not want to pull a new devtools-source-map into anything else.

**Comment by tromey** [comment]
Once that PR lands I plan to rev source-map, then devtools-source-map; then land it all in M-C.  Hopefully tomorrow.

**Pull request merged**
