### PR TITLE
pubish storybook

### PR DESCRIPTION
**Pull request by jasonLaster**
This PR adds [storybook-deployer](https://github.com/kadirahq/storybook-deployer/blob/master/bin/storybook_to_ghpages). 

It updates the [gh-pages](https://github.com/devtools-html/devtools-core/tree/gh-pages) branch here.

Unfortunately, it's not publishing the site when the branch is updated.

CC @clarkbw, @juliandescottes 

#### error message
screen shot 2016-12-30 at 11 45 53 am

#### settings
screen shot 2016-12-30 at 11 45 39 am

### CODE REVIEW

**Comment by gasolin** [comment]
I just made some ghpage auto deploy scripts to simplify the deploy process (via Travis CI). 
https://github.com/gasolin/ghpage-auto-deploy

The same script updated my homepage when I commit something to github.

**Comment by irfanhudda** [comment]
@jasonLaster I can see the storybook on [https://devtools-html.github.io/devtools-core](https://devtools-html.github.io/devtools-core). I guess this needs to be merged or closed.

**Comment by clarkbw** [comment]
I'm seeing the gh-page, maybe this was just a roll out issue?

**Comment by jasonLaster** [comment]
Thanks @irfanhudda, @gasolin.

I like @gasolin's approach with travis. The other big constraint is that we want storybook to be hosted in its own path

`https://devtools-html.github.io/devtools-core/storybook` 

which we can do with @gasolin's travis approach. I'm going to close this now and we can tackle it later.

**Pull request closed without merging**
